# Generated by Django 6.0.2 on 2026-02-07 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('term_months', models.IntegerField(default=6)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('released', 'Released (Active)'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('credit_score_at_application', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('escrow_wallet_address', models.CharField(blank=True, max_length=56)),
                ('amount_disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('milestones', models.JSONField(default=list)),
                ('current_milestone', models.IntegerField(default=0)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('assessment_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='crops.cropassessment')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('on_time', 'On Time'), ('late', 'Late'), ('partial', 'Partial'), ('auto_deducted', 'Auto-Deducted from Sale')], default='on_time', max_length=20)),
                ('transaction_hash', models.CharField(blank=True, max_length=64)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
                ('source_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_repayments', to='marketplace.order')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
    ]
